name: cvllm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi==0.110.0
      - uvicorn==0.29.0
      - pydantic==1.10.14
      - sqlmodel==0.0.16
      - transformers==4.39.3
      - langchain==0.1.14
      - langchain-community==0.0.30
      - sentence-transformers==2.2.2
      - faiss-cpu==1.7.4
      - peft==0.10.0
      - passlib[bcrypt]==1.7.4
      - python-jose==3.3.0
      - pdfminer.six==20221105
      - pandas==1.5.3
      - plotly==5.21.0
      - torch==2.1.2
      - gradio==3.50.2
      - accelerate==0.28.0