version: '3.9'

services:
  app:
    build: 
      context: .
      args:
        HF_TOKEN: ${HF_TOKEN}
    container_name: cvllm
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn python_finetune.startup:app --host 0.0.0.0 --port 8000 --reload
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  frontend:
    image: nginx:alpine
    container_name: cvllm
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro